name: "Build and publish"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node.JS"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # TODO: versioning: git version + npm version

      - name: "Restore dependencies"
        run: "npm ci"

      - name: "Build"
        run: "npm run build -- --configuration=production"

      - name: "Lint"
        run: "npm run lint"

      # TODO: run tests

      - name: "Publish artifacts to CI"
        uses: actions/upload-artifact@v4
        with:
          name: "Artifacts"
          retention-days: 14
          path: HyruleCompendium/dist/hyrule-compendium/

      - name: Publish artifacts to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/tesla-configurator/browser

  upload_doc:
    name: "Publish GitHub Pages"
    needs: "Build"
    runs-on: "ubuntu-latest"
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
